name: Deploy Backend to DigitalOcean

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Exit immediately if a command exits with a non-zero status.
            set -e

            # --- Define a reusable function to wait for a deployment ---
            wait_for_deployment() {
              local deployment_name="$1"
              echo "--> Waiting for worker deployment '$deployment_name' to register..."
              
              for i in {1..12}; do
                if docker compose exec -T temporal-admin-tools temporal --address temporal:7233 worker deployment describe --name "$deployment_name" &> /dev/null; then
                  echo "--> Deployment '$deployment_name' found."
                  return 0
                fi
                echo "Deployment not found yet. Attempt $i/12. Retrying in 5 seconds..."
                sleep 5
              done

              echo "!!> Worker deployment '$deployment_name' did not register in time. Aborting."
              exit 1
            }

            # --- Main Deployment Logic ---
            cd ~/loltimeanalysis/backend
            git pull

            export TEMPORAL_WORKER_BUILD_ID=${{ github.ref_name }}

            echo "--> Building and starting services with Build ID: $TEMPORAL_WORKER_BUILD_ID"
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

            wait_for_deployment "match-history-processor"
            wait_for_deployment "internal-processor"

            echo "--> Promoting Build ID to default for both deployments..."
            yes | docker compose exec -T temporal-admin-tools temporal worker deployment set-current-version \
              --deployment-name "match-history-processor" \
              --build-id "$TEMPORAL_WORKER_BUILD_ID"

            yes | docker compose exec -T temporal-admin-tools temporal worker deployment set-current-version \
              --deployment-name "internal-processor" \
              --build-id "$TEMPORAL_WORKER_BUILD_ID"

            echo "✅ Deployment successful for Build ID: $TEMPORAL_WORKER_BUILD_ID"
