name: Deploy Frontend to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          # Tell the cache where to find the lock file
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        # Run npm install from inside the frontend directory
        working-directory: ./frontend
        run: npm install

      - name: Build Project
        # Run the build from inside the frontend directory
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          # The source path is now frontend/dist/
          source: "frontend/dist/"
          target: "/var/www/yourdomain.com/html"
