name: Deploy Frontend to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # --- NEW DIAGNOSTIC STEP ---
      - name: Debug File Structure and Configs
        working-directory: ./frontend
        run: |
          echo "--- Listing all files recursively ---"
          ls -R
          echo ""
          echo "--- Contents of tsconfig.json ---"
          cat tsconfig.json
          echo ""
          echo "--- Contents of tsconfig.app.json ---"
          cat tsconfig.app.json
          echo ""

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Project
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "frontend/dist/"
          target: "/var/www/yourdomain.com/html"
